'''
Created on Jul 5, 2023

@author: Famenontsoa
'''

from AmadeusDecoder.utilities.ConfigReader import ConfigReader

# Company information
COMPANY_NAME = None
COMPANY_CURRENCY_NAME = None
COMPANY_CURRENCY_CODE = None
COMPANY_LANGUAGE_CODE = None
REGIONAL_COUNTRIES = []

#Saving File Tools
FILE_PROTOCOL = []

# Email source
EMAIL_PNR = {}
EMAIL_SENDING_ERROR_NOTIFICATION_RECIPIENTS = []
EMAIL_SENDING_ERROR_NOTIFICATION = {}
ANOMALY_EMAIL_SENDER = {}
PNR_NOT_FETCHED_NOTIFICATION_SENDER = {}
FEE_REQUEST_SENDER = {}
FEE_REQUEST_RECIPIENT = []
PNR_PARSING_ERROR_NOTIFICATION_SENDER = {}
PNR_PARSING_ERROR_NOTIFICATION_RECIPIENTS = []

# EMD parser tools
AIRPORT_AGENCY_CODE = []
SPECIAL_EMD_DESCRIPTION = []
NOT_FEED = []
EMD_IDENTIFIER = []
PNR_NUMBER_IDENTIFIER = []
PNR_TYPE = []
EMD_STATUSES = {}
EMD_DESCRIPTION_IDENTIFIER = []
EMD_ISSUING_DATE_IDENTIFIER = []
EMD_PAYMENT_METHOD_IDENTIFIER = []
NO_ADC_IDENTIFIER = []
COST_MODIFICATION_IDENTIFIER = []
COST_DETAIL_IDENTIFIER = []

# TST parser tools
SPECIAL_AGENCY_CODE = []
PASSENGER_DESIGNATIONS = []
TST_IDENTIFIER = []
TICKET_IDENTIFIER = []
COST_IDENTIFIER = []
TST_FARE_IDENTIFIER = []
TST_FARE_EQUIV_IDENTIFIER = []
TST_TOTAL_IDENTIFIER = []
TST_GRAND_TOTAL_IDENTIFIER = []

# Zenith parser tools
PASSENGER_TYPES = []
ZENITH_PASSENGER_DESIGNATIONS = []
E_TICKET_POSSIBLE_FORMAT = []
ITINERARY_HEADER_POSSIBLE_FORMAT = []
HEADER_NAMES = []
SERVICE_CARRIER = []

CURRENT_TRAVEL_AGENCY_IDENTIFIER = []
NON_RELEVANT_IDENTIFIER_FOR_PASSENGER = []

ITINERARY_NAME = []
ZENITH_COST_DETAIL_IDENTIFIER = []
ANCILLARIES_IDENTIFIER = []
NOT_EMITTED_PNR_START_IDENTIFIER = []
NOT_EMITTED_PNR_START_PASSENGER = []
NOT_EMITTED_PNR_START_BOOKING = []
NOT_EMITTED_PNR_START_BOOKING_COST = []
NOT_EMITTED_PNR_START_OPC = []
NOT_EMITTED_PNR_END_OPC = []
TO_BE_EXCLUDED_PNR_RECIPIENT_EMAIL = []

EMD_REFERENCE_START = []
EMD_EXPIRY_DATE_START = []
EMD_COMMENT_START = []
EMD_COST_START = []

MAIN_PNR_NUMBER_START_IDENTIFIER = []
PASSPORT_IDENTIFIER = []
PASSENGER_IDENTIFIER = []
PAYMENT_RECEIPT_IDENTIFIER = []
TOTAL_IDENTIFIER = []
PASSENGER_WORD_IDENTIFIER = []
PAYMENT_METHOD_IDENTIFIER = []
ISSUING_DATE_IDENTIFIER = []
ISSUING_OFFICE_IDENTIFIER = []
ISSUING_AGENT_IDENTIFIER = []
COST_WORD_IDENTIFIER = []
MODIFICATION_IDENTIFIER = []
TAX_IDENTIFIER = []
RECEIPT_IDENTIFIER = []
CUSTOMER_NAME_IDENTIFIER = []
ITINERARY_AIRPORT_IATA_CODE_IDENTIFIER = []

# Zenith receipt parser tools
PAYMENT_OPTIONS = []
TICKET_NUMBER_PREFIX = []
TO_BE_EXCLUDED_KEY_KEYWORDS = []
STARTED_PROCESS_DATE = None
TICKET_PAYMENT_PART = []
ADJUSTMENT_PART = []
EMD_CANCELLATION_PART = []
TICKET_CANCELLATION_PART = []
PENALTY_PART = []
AGENCY_FEE_PART = []
EMD_NO_NUMBER_POSSIBLE_DESIGNATION = []
DEFAULT_ASSIGNED_PASSENGER_ON_OBJECT = []
EMD_BALANCING_STATEMENT_PART = []

# Ticket parser tools
TICKET_MAIN_IDENTIFIER = []
RELATED_PNR_NUMBER_IDENTIFIER = []
TICKET_ISSUING_DATE_IDENTIFIER = []
ALL_POSSIBLE_TICKET_STATUSES = []
TICKET_IT_FARE_IDENTIFIER = []
TICKET_NO_ADC_IDENTIFIER = []
TICKET_COST_MODIFICATION_IDENTIFIER = []
PRIME_TICKET_IDENTIFIER = []
INVOL_REMOTE_IDENTIFIER = []
CREDIT_NOTE_TICKET_IDENTIFIER = []
GP_TICKET_IDENTIFIER = []
TICKET_COST_DETAIL_IDENTIFIER = []

# Fee request tools
FEE_REQUEST_RESPONSE_RECIPIENT = []
FEE_DECREASE_REQUEST_RESPONSE_SENDER = []
FEE_DECREASE_REQUEST_RESPONSE_RECIPIENTS = []

# Report email
FEE_HISTORY_REPORT_LOCAL_RECIPIENTS = []
FEE_HISTORY_REPORT_CUSTOMER_RECIPIENTS = []

# PNR parser tools
PNR_IDENTIFIER = []
MAIN_PNR_TYPE = []
DUPLICATE_PNR_IDENTIFIER = []
SPLIT_PNR_IDENTIFIER = []
TO_BE_EXCLUDED_LINE = []
CONTACT_TYPES = []
CONTACT_TYPE_NAMES = {}
TICKET_LINE_IDENTIFIER = []
SECOND_DEGREE_TICKET_LINE_IDENTIFIER = []
REMARK_IDENTIFIER = []
PNR_PASSENGER_DESIGNATIONS = []
POSSIBLE_COST_CURRENCY = []
AM_H_LINE_IDENTIFIER = []
ABSOLUTE_PATH_SERVICE_RUNNER = {}


# Get all coutries
COUTRIES_DATA = []

# Get department, city from France
DEPARTMENTS_FRANCE = []
MUNICIPALITIES_FRANCE = []

ConfigReader().load_config()