'''
Created on Jul 5, 2023

@author: Famenontsoa
'''

# Company information
COMPANY_NAME = None
COMPANY_CURRENCY_NAME = None
COMPANY_CURRENCY_CODE = None
COMPANY_LANGUAGE_CODE = None

# Email source
EMAIL_PNR = {}
EMAIL_SENDING_ERROR_NOTIFICATION_RECIPIENTS = []
EMAIL_SENDING_ERROR_NOTIFICATION = {}
ANOMALY_EMAIL_SENDER = {}
PNR_NOT_FETCHED_NOTIFICATION_SENDER = {}
FEE_REQUEST_SENDER = {}
PNR_PARSING_ERROR_NOTIFICATION_SENDER = {}
PNR_PARSING_ERROR_NOTIFICATION_RECIPIENTS = []

# EMD parser tools
AIRPORT_AGENCY_CODE = []
SPECIAL_EMD_DESCRIPTION = []
NOT_FEED = []
EMD_IDENTIFIER = []
PNR_NUMBER_IDENTIFIER = []
PNR_TYPE = []
EMD_STATUSES = {}
EMD_DESCRIPTION_IDENTIFIER = []
EMD_ISSUING_DATE_IDENTIFIER = []
EMD_PAYMENT_METHOD_IDENTIFIER = []
NO_ADC_IDENTIFIER = []
COST_MODIFICATION_IDENTIFIER = []
COST_DETAIL_IDENTIFIER = []

