# Generated by Django 4.0.6 on 2022-08-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0009_currency_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='rate',
        ),
    ]
