# Generated by Django 4.0.6 on 2022-09-02 08:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0021_office_code_pnr_agency_alter_pnr_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='otherinformations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=20),
        ),
        migrations.AddField(
            model_name='pnr',
            name='ssr',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=None), null=True, size=None),
        ),
    ]
