# Generated by Django 4.0.6 on 2022-09-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0034_alter_invoice_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='follow',
        ),
        migrations.AddField(
            model_name='invoice',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='AmadeusDecoder.user'),
        ),
    ]
