# Generated by Django 4.0.6 on 2022-09-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0036_alter_invoicedetails_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrairsegments',
            name='segmentorder',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='AmadeusDecoder.ticket'),
        ),
        migrations.AlterField(
            model_name='pnrairsegments',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='AmadeusDecoder.pnr'),
        ),
        migrations.AlterField(
            model_name='pnrairsegments',
            name='servicecarrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline', to='AmadeusDecoder.airline'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='AmadeusDecoder.ticket'),
        ),
        migrations.AlterField(
            model_name='tickethistories',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='AmadeusDecoder.ticket'),
        ),
    ]
