# Generated by Django 4.0.6 on 2022-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0049_specialservicerequestpassengersegment_ssr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialservicerequestpassengersegment',
            name='order_line',
            field=models.CharField(default='', max_length=10),
        ),
    ]
