# Generated by Django 4.0.6 on 2022-09-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0053_confirmationdeadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationdeadline',
            old_name='deadline',
            new_name='doc_date',
        ),
    ]
