# Generated by Django 4.0.6 on 2022-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0063_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='status_value',
            field=models.IntegerField(default=0),
        ),
    ]
