# Generated by Django 4.0.6 on 2022-09-30 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0067_alter_pnr_system_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
