# Generated by Django 4.0.6 on 2022-10-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0070_notification_alter_user_is_active'),
        ('AmadeusDecoder', '0071_alter_pnr_system_creation_date'),
    ]

    operations = [
    ]
