# Generated by Django 4.0.6 on 2022-10-06 11:18

import AmadeusDecoder.models.BaseModel
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0077_ticket_payment_option_alter_pnr_system_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 14, 18, 51, 88974)),
        ),
        migrations.CreateModel(
            name='TicketPassengerTST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tst_parts', to='AmadeusDecoder.passenger')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tst_parts', to='AmadeusDecoder.ticket')),
            ],
            options={
                'db_table': 't_ticket_passenger_tst',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
