# Generated by Django 4.0.6 on 2022-10-07 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0080_rename_servicefees_servicefeesmercure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='AmadeusDecoder.pnr'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='AmadeusDecoder.ticket'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 11, 46, 58, 18448)),
        ),
    ]
