# Generated by Django 4.0.6 on 2022-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0088_alter_pnrairsegments_timecheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrairsegments',
            name='flightclass',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
