# Generated by Django 4.0.7 on 2022-10-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0090_comment_state_ticketpassengersegment_fare_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='pnr_number',
            new_name='document_number',
        ),
    ]
