# Generated by Django 4.0.7 on 2022-10-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0093_merge_20221017_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='fare',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='tax',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='total',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
    ]
