# Generated by Django 3.2.15 on 2022-10-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0093_merge_20221017_1147'),
        ('AmadeusDecoder', '0095_comment_response_model_creation'),
    ]

    operations = [
    ]
