# Generated by Django 3.2.15 on 2022-10-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0096_merge_20221017_1506'),
        ('AmadeusDecoder', '0098_notification_creation_date'),
    ]

    operations = [
    ]
