# Generated by Django 3.2.15 on 2022-10-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0100_merge_20221021_1715'),
        ('AmadeusDecoder', '0106_pnrhistory_agent_code'),
        ('AmadeusDecoder', '0106_user_user_copying_model_creation'),
    ]

    operations = [
    ]
