# Generated by Django 4.0.6 on 2022-11-01 04:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0117_remove_pnrhistory_parent_pnr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrhistory',
            name='children_pnr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=20),
        ),
    ]
