# Generated by Django 4.0.6 on 2022-11-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0125_merge_20221108_1218'),
        ('AmadeusDecoder', '0125_merge_20221108_1421'),
        ('AmadeusDecoder', '0125_merge_20221108_1536'),
    ]

    operations = [
    ]
