# Generated by Django 4.0.6 on 2022-11-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0126_merge_20221108_1602'),
        ('AmadeusDecoder', '0128_pnr_is_invoiced_passengerinvoice'),
    ]

    operations = [
    ]
