# Generated by Django 4.0.6 on 2022-11-15 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0132_servicefeesprime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercopying',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
