# Generated by Django 4.0.6 on 2022-11-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0138_regionalflight_regionalflight_unique_region_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_regional',
            field=models.BooleanField(default=0),
        ),
    ]
