# Generated by Django 4.0.7 on 2022-11-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0139_fee_newest_cost'),
        ('AmadeusDecoder', '0140_alter_ticket_is_regional'),
    ]

    operations = [
    ]
