# Generated by Django 3.2.15 on 2022-11-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0139_fee_newest_cost'),
        ('AmadeusDecoder', '0140_alter_ticket_is_regional'),
    ]

    operations = [
    ]
