# Generated by Django 4.0.7 on 2022-11-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0141_merge_20221121_1325'),
        ('AmadeusDecoder', '0142_merge_0139_fee_newest_cost_0141_alter_pnr_agent_code'),
    ]

    operations = [
    ]
