# Generated by Django 3.2.15 on 2022-11-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0151_pnr_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reducepnrfeerequest',
            name='pnr',
            field=models.ForeignKey(default='1442', on_delete=django.db.models.deletion.CASCADE, related_name='pnr', to='AmadeusDecoder.pnr'),
            preserve_default=False,
        ),
    ]
