# Generated by Django 4.0.6 on 2022-11-28 10:46

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0152_othersfee_passenger_ticketpassengersegment_other_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othersfee',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='ticketpassengersegment',
            name='other_fee',
        ),
        migrations.CreateModel(
            name='OtherFeeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_segments', to='AmadeusDecoder.othersfee')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others_fees', to='AmadeusDecoder.passenger')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_segments', to='AmadeusDecoder.pnrairsegments')),
            ],
            options={
                'db_table': 't_other_fees_segment',
            },
            bases=(AmadeusDecoder.models.BaseModel.BaseModel, models.Model),
        ),
    ]
