# Generated by Django 4.0.6 on 2022-11-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0154_alter_othersfee_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
