# Generated by Django 4.0.7 on 2022-12-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0168_merge_20221206_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinvoice',
            name='invoice_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.invoice'),
        ),
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
