# Generated by Django 4.0.6 on 2022-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0180_passengerinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_subjected_to_fees',
            field=models.BooleanField(default=1),
        ),
    ]
