# Generated by Django 4.0.7 on 2022-12-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0182_pnrpassenger_order'),
        ('AmadeusDecoder', '0184_passengerinvoice_other_fee_passengerinvoice_status'),
    ]

    operations = [
    ]
