# Generated by Django 3.2.15 on 2022-12-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0183_merge_20221228_1710'),
        ('AmadeusDecoder', '0184_passengerinvoice_other_fee_passengerinvoice_status'),
    ]

    operations = [
    ]
