# Generated by Django 3.2.15 on 2022-12-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0185_merge_20221228_1749'),
        ('AmadeusDecoder', '0185_merge_20221229_0830'),
    ]

    operations = [
    ]
