# Generated by Django 3.2.15 on 2023-01-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0186_merge_20221229_1036'),
        ('AmadeusDecoder', '0187_merge_20221230_0941'),
        ('AmadeusDecoder', '0190_merge_20221231_0100'),
    ]

    operations = [
    ]
