# Generated by Django 4.0.7 on 2023-01-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0191_alter_client_date_creation'),
        ('AmadeusDecoder', '0192_pnrairsegments_is_open'),
    ]

    operations = [
    ]
