# Generated by Django 3.2.15 on 2023-01-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0191_merge_20230102_1735'),
        ('AmadeusDecoder', '0193_merge_20230103_1719'),
    ]

    operations = [
    ]
