# Generated by Django 4.0.6 on 2023-01-06 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0195_merge_20230106_0955'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        migrations.AddField(
            model_name='reducepnrfeerequest',
            name='user_responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduce_pnr_fee_request_responder', to=settings.AUTH_USER_MODEL),
        ),
    ]
