# Generated by Django 3.2.15 on 2023-01-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0199_merge_20230110_1347'),
        ('AmadeusDecoder', '0201_merge_20230112_1040'),
    ]

    operations = [
    ]
