# Generated by Django 4.0.7 on 2023-01-12 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0204_merge_20230112_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFetched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('pnr_creation', models.CharField(max_length=100)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_pnr_not_fetched',
            },
        ),
    ]
