# Generated by Django 4.0.6 on 2023-01-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0208_merge_20230117_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_data', to='AmadeusDecoder.ticket'),
        ),
    ]
