# Generated by Django 4.0.6 on 2023-01-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0215_merge_20230124_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrairsegments',
            name='air_segment_status',
            field=models.IntegerField(default=1),
        ),
    ]
