# Generated by Django 4.0.7 on 2023-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0219_merge_20230127_1636'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='othersfee',
        #     name='creation_date',
        #     field=models.DateField(auto_now=True, null=True),
        # ),
    ]
