# Generated by Django 4.0.6 on 2023-02-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0223_merge_20230204_1035'),
        ('AmadeusDecoder', '0224_passengerinvoice_invoice_number_and_more'),
    ]

    operations = [
    ]
