# Generated by Django 3.2.15 on 2023-02-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0224_auto_20230204_1520'),
        ('AmadeusDecoder', '0225_merge_20230204_1308'),
    ]

    operations = [
    ]
