# Generated by Django 4.0.6 on 2023-02-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0226_merge_20230206_0608'),
        ('AmadeusDecoder', '0226_othersfee_other_fee_status'),
    ]

    operations = [
    ]
