# Generated by Django 3.2.15 on 2023-02-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0227_merge_20230207_1048'),
        ('AmadeusDecoder', '0227_merge_20230208_1748'),
    ]

    operations = [
    ]
