# Generated by Django 3.2.15 on 2023-02-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0226_merge_20230204_1618'),
        ('AmadeusDecoder', '0231_rename_is_subjected_too_fee_othersfee_is_subjected_to_fee'),
    ]

    operations = [
    ]
