# Generated by Django 4.0.7 on 2023-02-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0225_merge_20230206_1416'),
        ('AmadeusDecoder', '0231_rename_is_subjected_too_fee_othersfee_is_subjected_to_fee'),
    ]

    operations = [
    ]
