# Generated by Django 3.2.15 on 2023-03-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0236_merge_20230227_1742'),
        ('AmadeusDecoder', '0236_passengerinvoice_status_ticket_is_deposit'),
    ]

    operations = [
    ]
