# Generated by Django 4.1.7 on 2023-03-16 12:34

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0238_ticket_is_issued_outside'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSubcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=200, null=True)),
                ('subcontracting_cost', models.DecimalField(decimal_places=4, default=0, max_digits=11)),
            ],
            options={
                'db_table': 't_office_subcontractor',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='officesubcontractor',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_office_subcontractor'),
        ),
    ]
