# Generated by Django 3.2.15 on 2023-03-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0239_merge_20230315_1747'),
        ('AmadeusDecoder', '0239_officesubcontractor_passengerinvoice_status_and_more'),
    ]

    operations = [
    ]
