# Dockerfile for the database
FROM postgres:15

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=db_flight_issoufali

# # Copy SQL scripts into the container
# COPY db_flight_issoufali01122023.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432
