# Generated by Django 4.0.6 on 2022-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0002_alter_airport_elevation_ft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
