# Generated by Django 4.0.6 on 2022-08-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0003_alter_airport_iata_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
