# Generated by Django 4.0.6 on 2022-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
