# Generated by Django 4.0.6 on 2022-08-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0008_alter_pnr_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='currency_rate', to='AmadeusDecoder.currencyrate'),
            preserve_default=False,
        ),
    ]
