# Generated by Django 4.0.6 on 2022-08-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0010_remove_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.currency'),
        ),
    ]
