# Generated by Django 4.0.6 on 2022-09-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0017_remove_contact_pnr_contact_pnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='exportstatus',
        ),
        migrations.AddField(
            model_name='pnr',
            name='status',
            field=models.CharField(default='Non émis', max_length=100),
        ),
    ]
