# Generated by Django 4.0.6 on 2022-09-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0019_remove_contact_pnr_contact_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='AmadeusDecoder.pnr'),
        ),
    ]
