# Generated by Django 4.0.6 on 2022-09-02 08:32

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0022_pnr_otherinformations_pnr_ssr'),
    ]

    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name='pnr',
            name='ssr',
        ),
    ]
