# Generated by Django 4.0.6 on 2022-09-02 08:39

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0023_alter_pnr_ssr'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='pnr',
            name='ssr',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
