# Generated by Django 4.0.6 on 2022-09-02 08:46

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0024_alter_pnr_ssr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='ssr',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
