# Generated by Django 4.0.6 on 2022-09-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0025_alter_pnr_ssr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerattribute',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='AmadeusDecoder.passenger'),
        ),
        migrations.AlterField(
            model_name='pnrpassenger',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='AmadeusDecoder.pnr'),
        ),
    ]
