# Generated by Django 4.0.6 on 2022-09-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0027_passengerattribute_type_alter_pnrpassenger_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='order',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pnrpassenger',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='AmadeusDecoder.passenger'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='AmadeusDecoder.pnr'),
        ),
    ]
