# Generated by Django 4.0.6 on 2022-09-02 12:07

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0028_passenger_order_alter_pnrpassenger_passenger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='type',
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(default='Simple', max_length=200),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='AmadeusDecoder.client'),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'Information': 'Unknown'}),
        ),
    ]
