# Generated by Django 4.0.6 on 2022-09-02 12:15

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0029_remove_clientaddress_type_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
