# Generated by Django 4.0.6 on 2022-09-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0030_alter_clientaddress_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='openingstatus',
            field=models.BooleanField(default=0),
        ),
    ]
