# Generated by Django 4.0.6 on 2022-09-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0031_pnr_openingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pnr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='AmadeusDecoder.pnr'),
        ),
    ]
