# Generated by Django 4.0.6 on 2022-09-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0035_remove_invoice_follow_invoice_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='AmadeusDecoder.invoice'),
        ),
    ]
