# Generated by Django 4.0.6 on 2022-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0037_pnrairsegments_segmentorder_alter_payment_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
    ]
