# Generated by Django 4.0.6 on 2022-09-10 12:40

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0038_remove_ticket_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPassengerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='AmadeusDecoder.passenger')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='AmadeusDecoder.pnrairsegments')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_parts', to='AmadeusDecoder.ticket')),
            ],
            options={
                'db_table': 't_ticket_passenger_segment',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
