# Generated by Django 4.0.6 on 2022-09-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0039_ticketpassengersegment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('number',), name='unique_ticket'),
        ),
    ]
