# Generated by Django 4.0.6 on 2022-09-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0040_ticket_unique_ticket'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pnrpassenger',
            constraint=models.UniqueConstraint(fields=('pnr', 'passenger'), name='unique_pnr_passenger'),
        ),
    ]
