# Generated by Django 4.0.6 on 2022-09-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0041_pnrpassenger_unique_pnr_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpassengersegment',
            name='passenger',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='AmadeusDecoder.passenger'),
        ),
    ]
