# Generated by Django 4.0.6 on 2022-09-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0042_remove_ticketpassengersegment_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='is_child',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pnr',
            name='is_parent',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pnr',
            name='parent_pnr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='AmadeusDecoder.pnr'),
        ),
    ]
