# Generated by Django 4.0.6 on 2022-09-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0043_pnr_is_child_pnr_is_parent_pnr_parent_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='AmadeusDecoder.passenger'),
        ),
    ]
