# Generated by Django 4.0.6 on 2022-09-15 14:29

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0046_alter_ticket_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('freeflowtext', models.BooleanField(default=False)),
                ('suppliedbyairline', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_ssr',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.CreateModel(
            name='SpecialServiceRequestDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('ssr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='AmadeusDecoder.specialservicerequest')),
            ],
            options={
                'db_table': 't_ssr_description',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='specialservicerequest',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_ssr'),
        ),
    ]
