# Generated by Django 4.0.6 on 2022-09-19 10:16

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0047_specialservicerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnrRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_pnr_remark',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_remark',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.CreateModel(
            name='SpecialServiceRequestPassengerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssr_list', to='AmadeusDecoder.passenger')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssr_list', to='AmadeusDecoder.pnrairsegments')),
                ('ssr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssr_passenger_segment', to='AmadeusDecoder.specialservicerequest')),
            ],
            options={
                'db_table': 't_ssr_passenger_segment',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='remark',
            constraint=models.UniqueConstraint(fields=('type', 'code'), name='unique_remark'),
        ),
        migrations.AddField(
            model_name='pnrremark',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='AmadeusDecoder.pnr'),
        ),
        migrations.AddField(
            model_name='pnrremark',
            name='remark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='AmadeusDecoder.remark'),
        ),
    ]
