# Generated by Django 4.0.6 on 2022-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0048_pnrremark_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialservicerequestpassengersegment',
            name='ssr_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
