# Generated by Django 4.0.6 on 2022-09-22 10:23

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0050_specialservicerequestpassengersegment_order_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialServiceRequestBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssr_text', models.CharField(default='', max_length=200)),
                ('order_line', models.CharField(default='', max_length=10)),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssr_list', to='AmadeusDecoder.pnr')),
                ('ssr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_ssr', to='AmadeusDecoder.specialservicerequest')),
            ],
            options={
                'db_table': 't_ssr_base',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.CreateModel(
            name='SpecialServiceRequestPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_ssr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='AmadeusDecoder.specialservicerequestbase')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssr_list', to='AmadeusDecoder.passenger')),
            ],
            options={
                'db_table': 't_ssr_passenger',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.CreateModel(
            name='SpecialServiceRequestSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_ssr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='AmadeusDecoder.specialservicerequestbase')),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssr_list', to='AmadeusDecoder.pnrairsegments')),
            ],
            options={
                'db_table': 't_ssr_segment',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.DeleteModel(
            name='SpecialServiceRequestPassengerSegment',
        ),
    ]
