# Generated by Django 4.0.6 on 2022-09-22 11:49

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0051_specialservicerequestbase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='AmadeusDecoder.specialservicerequestbase')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_ssrs', to='AmadeusDecoder.ticket')),
            ],
            options={
                'db_table': 't_ticket_ssr',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
