# Generated by Django 4.0.6 on 2022-09-22 17:27

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0052_ticketssr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('free_flow_text', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_deadline', to='AmadeusDecoder.pnrairsegments')),
                ('ssr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_deadline', to='AmadeusDecoder.specialservicerequestbase')),
            ],
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
