# Generated by Django 4.0.6 on 2022-09-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0054_rename_deadline_confirmationdeadline_doc_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confirmationdeadline',
            table=None,
        ),
    ]
