# Generated by Django 4.0.6 on 2022-09-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0055_alter_confirmationdeadline_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confirmationdeadline',
            table='t_confirmation_deadline',
        ),
    ]
