# Generated by Django 4.0.6 on 2022-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0056_alter_confirmationdeadline_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
