# Generated by Django 4.0.6 on 2022-09-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0058_alter_confirmationdeadline_doc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrairsegments',
            name='segment_type',
            field=models.CharField(default='Vol', max_length=100),
        ),
        migrations.AlterField(
            model_name='pnrairsegments',
            name='codedest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='AmadeusDecoder.airport', to_field='iata_code'),
        ),
        migrations.AlterField(
            model_name='pnrairsegments',
            name='codeorg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport', to='AmadeusDecoder.airport', to_field='iata_code'),
        ),
    ]
