# Generated by Django 4.0.6 on 2022-09-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0059_pnrairsegments_segment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='is_duplicated',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pnr',
            name='is_splitted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pnrairsegments',
            name='segment_type',
            field=models.CharField(default='Flight', max_length=100),
        ),
    ]
