# Generated by Django 4.0.6 on 2022-09-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0052_remove_user_type_alter_user_password'),
        ('AmadeusDecoder', '0060_pnr_is_duplicated_pnr_is_splitted_and_more'),
    ]

    operations = [
    ]
