# Generated by Django 4.0.6 on 2022-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0062_alter_pnr_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
