# Generated by Django 4.0.6 on 2022-09-30 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0064_pnr_status_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pnr',
            old_name='creationdate',
            new_name='gds_creation_date',
        ),
        migrations.AddField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 14, 51, 50, 200413)),
        ),
    ]
