# Generated by Django 4.0.7 on 2022-09-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0064_pnr_status_value'),
        ('AmadeusDecoder', '0065_user_last_login_time'),
    ]

    operations = [
    ]
