# Generated by Django 4.0.6 on 2022-09-30 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0066_alter_pnr_system_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 11, 54, 49, 651967, tzinfo=datetime.timezone.utc)),
        ),
    ]
