# Generated by Django 4.0.6 on 2022-09-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0066_merge_0064_pnr_status_value_0065_user_last_login_time'),
        ('AmadeusDecoder', '0068_alter_pnr_system_creation_date'),
    ]

    operations = [
    ]
