# Generated by Django 4.0.7 on 2022-10-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0070_notification_alter_user_is_active'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='pnr',
        #     name='is_read',
        #     field=models.BooleanField(default=False),
        # ),
    ]
