# Generated by Django 4.0.7 on 2022-10-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0071_pnr_is_read'),
        ('AmadeusDecoder', '0072_merge_20221003_1201'),
    ]

    operations = [
    ]
