# Generated by Django 4.0.6 on 2022-10-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0072_merge_20221003_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passeport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='types',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 22, 9, 44, 88744)),
        ),
    ]
