# Generated by Django 4.0.6 on 2022-10-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0073_merge_0071_pnr_is_read_0072_merge_20221003_1201'),
        ('AmadeusDecoder', '0073_passenger_passeport_passenger_types_and_more'),
    ]

    operations = [
    ]
