# Generated by Django 4.0.6 on 2022-10-07 05:53

import AmadeusDecoder.models.BaseModel
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0079_remove_ticket_unique_ticket_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceFees',
            new_name='ServiceFeesMercure',
        ),
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 8, 52, 54, 964230)),
        ),
        migrations.AlterModelTable(
            name='servicefeesmercure',
            table='t_servicefees_sigm',
        ),
        migrations.CreateModel(
            name='ServiceFeesIssoufali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_interval', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('max_interval', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('last_update', models.DateTimeField(null=True)),
                ('last_update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_servicefees_issoufali',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='servicefeesissoufali',
            constraint=models.UniqueConstraint(fields=('min_interval', 'max_interval'), name='unique_service_fees'),
        ),
    ]
