# Generated by Django 4.1.1 on 2022-10-07 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0080_rename_servicefees_servicefeesmercure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 8, 53, 15, 495351)),
        ),
    ]
