# Generated by Django 4.1.1 on 2022-10-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0076_alter_pnr_system_creation_date_comment'),
        ('AmadeusDecoder', '0081_alter_pnr_system_creation_date'),
    ]

    operations = [
    ]
