# Generated by Django 4.0.6 on 2022-10-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0082_merge_20221007_1030'),
        ('AmadeusDecoder', '0085_alter_pnr_system_creation_date'),
    ]

    operations = [
    ]
