# Generated by Django 4.0.6 on 2022-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0086_merge_20221007_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='system_creation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
