# Generated by Django 4.0.7 on 2022-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0089_pnrairsegments_flightclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='fare',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='tax',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='total',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
    ]
