# Generated by Django 4.1.1 on 2022-10-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0091_pnrairsegments_segment_state_pnrhistory'),
        ('AmadeusDecoder', '0092_notification_user_id'),
    ]

    operations = [
    ]
