# Generated by Django 4.0.6 on 2022-10-18 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0092_ticket_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='emitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emitted_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
