# Generated by Django 3.2.15 on 2022-10-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0091_pnrairsegments_segment_state_pnrhistory'),
        ('AmadeusDecoder', '0092_notification_user_id'),
    ]

    operations = [
    ]
