# Generated by Django 4.0.6 on 2022-10-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0093_ticket_emitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrairsegments',
            name='segment_hk_sa',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
