# Generated by Django 4.0.6 on 2022-10-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0094_pnrairsegments_segment_hk_sa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_gp_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
