# Generated by Django 4.0.6 on 2022-10-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0095_ticket_ticket_gp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_gp_status',
            field=models.CharField(default='OK', max_length=10),
        ),
    ]
