# Generated by Django 4.0.7 on 2022-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0096_notification_document_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
