# Generated by Django 4.0.6 on 2022-10-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0096_alter_ticket_ticket_gp_status'),
        ('AmadeusDecoder', '0096_merge_20221017_1506'),
    ]

    operations = [
    ]
