# Generated by Django 4.0.6 on 2022-10-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0098_notification_is_pnr_ticketpassengersegment_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='exch_val',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issuing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rfnd_val',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_description',
            field=models.CharField(max_length=250, null=True),
        ),
        # migrations.AddField(
        #    model_name='ticketpassengersegment',
        #    name='fare',
        #    field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #    model_name='ticketpassengersegment',
        #    name='tax',
        #    field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #   model_name='ticketpassengersegment',
        #    name='total',
        #    field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
    ]
