# Generated by Django 4.0.7 on 2022-10-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0098_notification_creation_date'),
        ('AmadeusDecoder', '0098_notification_is_pnr_ticketpassengersegment_fare_and_more'),
    ]

    operations = [
    ]
