# Generated by Django 4.0.6 on 2022-10-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0099_merge_20221021_1111'),
        ('AmadeusDecoder', '0099_ticket_exch_val_ticket_issuing_date_ticket_rfnd_val_and_more'),
    ]

    operations = [
    ]
