# Generated by Django 4.0.6 on 2022-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0101_remove_notification_is_pnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='total_fees',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='total_tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='fare',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='tax',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
        # migrations.AddField(
        #     model_name='ticketpassengersegment',
        #     name='total',
        #     field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        # ),
    ]
