# Generated by Django 4.0.6 on 2022-10-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0102_invoicedetails_total_fees_invoicedetails_total_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='agent_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
