# Generated by Django 4.0.6 on 2022-10-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0100_merge_20221025_0743'),
        ('AmadeusDecoder', '0103_pnr_agent_code'),
    ]

    operations = [
    ]
