# Generated by Django 4.0.6 on 2022-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0104_merge_0100_merge_20221025_0743_0103_pnr_agent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrairsegments',
            name='other_segment_description',
            field=models.CharField(default='Auxiliary segment', max_length=200),
        ),
    ]
