# Generated by Django 4.0.6 on 2022-10-27 14:04

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0106_pnrhistory_agent_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationDeadlineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=6, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('free_flow_text', models.CharField(max_length=200, null=True)),
                ('doc_date', models.DateTimeField(null=True)),
                ('history_datetime', models.DateTimeField(null=True)),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_deadline_histories', to='AmadeusDecoder.pnrairsegments')),
                ('ssr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_deadline_histories', to='AmadeusDecoder.specialservicerequestbase')),
            ],
            options={
                'db_table': 't_confirmation_deadline_history',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
