# Generated by Django 4.0.6 on 2022-10-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0106_user_user_copying_model_creation'),
        ('AmadeusDecoder', '0107_confirmationdeadlinehistory'),
    ]

    operations = [
    ]
