# Generated by Django 4.0.6 on 2022-10-28 13:37

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0108_merge_20221028_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_currency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_company_info',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='companyinfo',
            constraint=models.UniqueConstraint(fields=('company_name',), name='unique_company'),
        ),
    ]
