# Generated by Django 4.1.1 on 2022-10-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0107_merge_20221027_1847'),
        ('AmadeusDecoder', '0109_companyinfo_ticketpassengersegment_fare_and_more'),
    ]

    operations = [
    ]
