# Generated by Django 4.0.6 on 2022-10-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0110_merge_20221031_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passenger_type',
            field=models.CharField(default='PAX', max_length=10),
        ),
        migrations.AddField(
            model_name='ticketpassengersegment',
            name='fare',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='ticketpassengersegment',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='ticketpassengersegment',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=11),
        ),
    ]
