# Generated by Django 4.0.6 on 2022-10-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0110_merge_20221031_1111'),
        ('AmadeusDecoder', '0111_ticket_passenger_type_ticketpassengersegment_fare_and_more'),
    ]

    operations = [
    ]
