# Generated by Django 4.0.6 on 2022-10-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0112_merge_20221031_1321'),
        ('AmadeusDecoder', '0112_merge_20221031_1526'),
    ]

    operations = [
    ]
