# Generated by Django 4.0.6 on 2022-10-31 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0113_merge_20221031_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='parent_pnr',
        ),
        migrations.AddField(
            model_name='pnr',
            name='children_pnr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=20),
        ),
    ]
