# Generated by Django 4.0.6 on 2022-10-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0115_pnr_parent_pnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnrhistory',
            name='parent_pnr',
        ),
    ]
