# Generated by Django 4.0.6 on 2022-10-31 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0116_remove_pnrhistory_parent_pnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnrhistory',
            name='parent_pnr_number',
        ),
        migrations.AddField(
            model_name='pnrhistory',
            name='parent_pnr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=20),
        ),
    ]
