# Generated by Django 4.0.6 on 2022-11-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0118_pnrhistory_children_pnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='agency_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
