# Generated by Django 4.0.6 on 2022-11-04 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0119_pnr_agency_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicefeesissoufali',
            table='t_servicefees_amount_based',
        ),
        migrations.AlterModelTable(
            name='servicefeesmercure',
            table='t_servicefees_flight_class_based',
        ),
        # migrations.CreateModel(
        #     name='PassengerInvoice',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('reference', models.CharField(max_length=100)),
        #         ('is_invoiced', models.BooleanField(default=False)),
        #         ('is_checked', models.BooleanField(default=True)),
        #         ('type', models.CharField(max_length=100)),
        #         ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.client')),
        #         ('fee', models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.fee')),
        #         ('pnr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_invoice', to='AmadeusDecoder.pnr')),
        #         ('ticket', models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket')),
        #         ('user_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'db_table': 't_passenger_invoice',
        #     },
        # ),
    ]
