# Generated by Django 4.0.6 on 2022-11-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0120_alter_servicefeesissoufali_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fare_type',
            field=models.CharField(default='F', max_length=4),
        ),
    ]
