# Generated by Django 4.0.7 on 2022-11-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0120_alter_servicefeesissoufali_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='order_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
