# Generated by Django 4.0.6 on 2022-11-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0121_alter_client_address_2_alter_client_city_and_more'),
        ('AmadeusDecoder', '0121_ticket_fare_type'),
    ]

    operations = [
    ]
