# Generated by Django 4.0.6 on 2022-11-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0123_passengerinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='status_value',
            field=models.IntegerField(default=1),
        ),
    ]
