# Generated by Django 4.1.1 on 2022-11-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0122_passengerinvoice'),
        ('AmadeusDecoder', '0124_alter_pnr_status_value'),
    ]

    operations = [
    ]
