# Generated by Django 4.1.1 on 2022-11-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0125_merge_20221108_1218'),
        ('AmadeusDecoder', '0125_merge_20221108_1421'),
    ]

    operations = [
    ]
