# Generated by Django 4.1.1 on 2022-11-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0125_merge_20221108_1536'),
        ('AmadeusDecoder', '0126_merge_20221108_1324'),
    ]

    operations = [
    ]
