# Generated by Django 4.0.7 on 2022-11-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0127_merge_20221108_1437'),
    ]

    operations = [
        migrations.AddField(
              model_name='pnr',
              name='is_invoiced',
              field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='PassengerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('is_checked', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.client')),
                ('fee', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.fee')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_invoice', to='AmadeusDecoder.pnr')),
                ('ticket', models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket')),
                ('user_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_passenger_invoice',
            },
        ),
    ]
