# Generated by Django 3.2.15 on 2022-11-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0129_merge_20221109_1333'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='pnr',
        #     name='is_invoiced',
        #     field=models.BooleanField(default=0),
        # ),
    ]
