# Generated by Django 4.0.6 on 2022-11-14 14:09

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0131_ticket_is_prime_ticket_issuing_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeesPrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('fee_value', models.DecimalField(decimal_places=4, default=0, max_digits=11)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fees_prime', to='AmadeusDecoder.companyinfo')),
            ],
            options={
                'db_table': 't_service_fees_prime',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
