# Generated by Django 4.0.7 on 2022-11-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0131_othersfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='classment',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='code_postal',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='complement',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='ct_num',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='intitule',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='site',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
