# Generated by Django 4.0.7 on 2022-11-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0133_client_ct_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='classment',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='complement',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='ct_num',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='ct_type',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='intitule',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='site',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
