# Generated by Django 3.2.15 on 2022-11-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0132_servicefeesprime'),
        ('AmadeusDecoder', '0134_alter_client_classment_alter_client_code_postal_and_more'),
    ]

    operations = [
    ]
