# Generated by Django 4.0.6 on 2022-11-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0133_alter_usercopying_user_id'),
        ('AmadeusDecoder', '0134_alter_client_classment_alter_client_code_postal_and_more'),
    ]

    operations = [
    ]
