# Generated by Django 4.0.6 on 2022-11-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0135_merge_20221115_1124'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicefeesprime',
            constraint=models.UniqueConstraint(fields=('company', 'type'), name='unique_service_fees_prime'),
        ),
    ]
