# Generated by Django 4.1.1 on 2022-11-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0135_merge_20221115_0932'),
        ('AmadeusDecoder', '0136_servicefeesprime_unique_service_fees_prime'),
    ]

    operations = [
    ]
