# Generated by Django 4.0.7 on 2022-11-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0135_merge_20221115_1006'),
        ('AmadeusDecoder', '0136_servicefeesprime_unique_service_fees_prime'),
    ]

    operations = [
    ]
