# Generated by Django 4.0.7 on 2022-11-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0137_merge_20221115_1539'),
        ('AmadeusDecoder', '0137_merge_20221116_0604'),
    ]

    operations = [
    ]
