# Generated by Django 4.0.6 on 2022-11-17 06:49

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0137_merge_20221116_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_flights', to='AmadeusDecoder.companyinfo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_as_regional', to='AmadeusDecoder.country')),
            ],
            options={
                'db_table': 't_company_regional_flight',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='regionalflight',
            constraint=models.UniqueConstraint(fields=('company', 'country'), name='unique_region_company'),
        ),
    ]
