# Generated by Django 4.0.7 on 2022-11-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0138_merge_20221116_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='newest_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=11),
        ),
    ]
