# Generated by Django 4.0.6 on 2022-11-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0139_ticket_is_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_regional',
            field=models.BooleanField(default=1),
        ),
    ]
