# Generated by Django 4.0.6 on 2022-11-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0140_alter_ticket_is_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='agent_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
