# Generated by Django 4.0.6 on 2022-11-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0139_fee_newest_cost'),
        ('AmadeusDecoder', '0141_alter_pnr_agent_code'),
    ]

    operations = [
    ]
