# Generated by Django 3.2.15 on 2022-11-21 17:56

import AmadeusDecoder.models.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0141_merge_20221120_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducePnrFeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=11)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=11)),
                ('system_creation_date', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduce_pnr_fee_request', to='AmadeusDecoder.fee')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduce_pnr_fee_request', to='AmadeusDecoder.pnr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduce_pnr_fee_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_reduce_pnr_fee_request',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
