# Generated by Django 4.1.1 on 2022-11-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0141_merge_20221118_1729'),
        ('AmadeusDecoder', '0142_merge_0139_fee_newest_cost_0141_alter_pnr_agent_code'),
        ('AmadeusDecoder', '0142_reducepnrfeerequest'),
    ]

    operations = [
    ]
