# Generated by Django 4.0.7 on 2022-11-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0143_merge_20221122_0822'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='othersfee',
            table='t_product',
        ),
    ]
