# Generated by Django 4.0.7 on 2022-11-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0144_alter_othersfee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='othersfee',
            table='t_other_fee',
        ),
    ]
