# Generated by Django 4.0.7 on 2022-11-22 12:50

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0145_alter_othersfee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=11, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=11)),
                ('tax', models.DecimalField(decimal_places=4, default=0.0, max_digits=11)),
                ('total', models.DecimalField(decimal_places=4, default=0.0, max_digits=11)),
                ('product_id', models.IntegerField()),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AmadeusDecoder.pnr')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AmadeusDecoder.ticket')),
            ],
            options={
                'db_table': 't_product',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
