# Generated by Django 4.0.6 on 2022-11-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0143_merge_20221122_1321'),
        ('AmadeusDecoder', '0146_product'),
    ]

    operations = [
    ]
