# Generated by Django 4.0.6 on 2022-11-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0144_reducepnrfeerequest_token'),
        ('AmadeusDecoder', '0147_merge_0143_merge_20221122_1321_0146_product'),
    ]

    operations = [
    ]
