# Generated by Django 4.0.6 on 2022-11-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0148_merge_20221123_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reducepnrfeerequest',
            name='pnr',
        ),
        migrations.AlterField(
            model_name='pnrhistory',
            name='agent_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
