# Generated by Django 4.0.7 on 2022-11-25 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0149_remove_reducepnrfeerequest_pnr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinvoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.client'),
        ),
    ]
