# Generated by Django 4.0.6 on 2022-11-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0149_remove_reducepnrfeerequest_pnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpassengersegment',
            name='other_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_fee_parts', to='AmadeusDecoder.othersfee'),
        ),
    ]
