# Generated by Django 4.0.6 on 2022-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0150_ticketpassengersegment_other_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpassengersegment',
            name='other_fee',
        ),
    ]
