# Generated by Django 4.0.7 on 2022-11-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0150_alter_passengerinvoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='AmadeusDecoder.client'),
        ),
    ]
