# Generated by Django 4.0.6 on 2022-11-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0153_remove_othersfee_passenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othersfee',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others_fees', to='AmadeusDecoder.ticket'),
        ),
    ]
