# Generated by Django 4.0.6 on 2022-11-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0151_pnr_customer'),
        ('AmadeusDecoder', '0155_othersfee_quantity'),
    ]

    operations = [
    ]
