# Generated by Django 4.1.1 on 2022-11-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0152_reducepnrfeerequest_pnr'),
        ('AmadeusDecoder', '0156_merge_0151_pnr_customer_0155_othersfee_quantity'),
    ]

    operations = [
    ]
