# Generated by Django 3.2.15 on 2022-12-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0152_reducepnrfeerequest_pnr'),
        ('AmadeusDecoder', '0156_merge_0151_pnr_customer_0155_othersfee_quantity'),
    ]

    operations = [
    ]
