# Generated by Django 4.1.1 on 2022-11-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0157_merge_20221128_1502'),
        ('AmadeusDecoder', '0157_merge_20221128_1700'),
    ]

    operations = [
    ]
