# Generated by Django 3.2.15 on 2022-11-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0157_merge_20221128_1502'),
        ('AmadeusDecoder', '0157_merge_20221128_1700'),
    ]

    operations = [
    ]
