# Generated by Django 4.0.7 on 2022-11-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0157_merge_20221128_1502'),
        ('AmadeusDecoder', '0157_merge_20221128_1700'),
    ]

    operations = [
    ]
