# Generated by Django 4.0.7 on 2022-11-28 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0158_merge_20221128_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pnr',
        ),
        migrations.AlterField(
            model_name='product',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='AmadeusDecoder.ticket'),
        ),
    ]
