# Generated by Django 4.0.7 on 2022-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0159_remove_product_pnr_alter_product_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
