# Generated by Django 3.2.15 on 2022-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0158_merge_20221129_0949'),
        ('AmadeusDecoder', '0160_remove_product_value_product_code'),
    ]

    operations = [
    ]
