# Generated by Django 4.0.7 on 2022-12-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0160_remove_product_value_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='departement',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
