# Generated by Django 4.1.1 on 2022-11-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0158_merge_20221129_0720'),
        ('AmadeusDecoder', '0160_remove_product_value_product_code'),
    ]

    operations = [
    ]
