# Generated by Django 4.0.6 on 2022-11-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0158_merge_20221129_0720'),
        ('AmadeusDecoder', '0161_merge_20221129_1002'),
    ]

    operations = [
    ]
