# Generated by Django 3.2.15 on 2022-11-29 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0158_merge_20221129_0720'),
        ('AmadeusDecoder', '0161_merge_20221129_1002'),
    ]

    operations = [
    ]
