# Generated by Django 4.1.1 on 2022-11-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0161_merge_20221129_1002'),
        ('AmadeusDecoder', '0161_merge_20221129_1219'),
    ]

    operations = [
    ]
