# Generated by Django 4.0.6 on 2022-11-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0161_merge_20221129_1219'),
        ('AmadeusDecoder', '0162_merge_20221129_1439'),
    ]

    operations = [
    ]
