# Generated by Django 4.1.1 on 2022-12-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0162_merge_20221130_1104'),
        ('AmadeusDecoder', '0163_merge_20221130_1313'),
    ]

    operations = [
    ]
