# Generated by Django 4.0.7 on 2022-12-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0162_passengerinvoice_is_quotation_and_more'),
        ('AmadeusDecoder', '0164_merge_20221201_0750'),
    ]

    operations = [
    ]
