# Generated by Django 3.2.15 on 2022-12-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0162_merge_20221129_1010'),
        ('AmadeusDecoder', '0165_merge_20221201_1747'),
    ]

    operations = [
    ]
