# Generated by Django 4.1.1 on 2022-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0166_auto_20221202_0757'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        migrations.AlterField(
            model_name='client',
            name='classment',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='complement',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ct_num',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ct_type',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='intitule',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='site',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
