# Generated by Django 4.0.7 on 2022-12-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0157_merge_20221201_1745'),
        ('AmadeusDecoder', '0167_passengerinvoice_status_alter_client_classment_and_more'),
    ]

    operations = [
    ]
