# Generated by Django 3.2.15 on 2022-12-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0167_passengerinvoice_status'),
        ('AmadeusDecoder', '0167_passengerinvoice_status_alter_client_classment_and_more'),
    ]

    operations = [
    ]
