# Generated by Django 3.2.15 on 2022-12-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0157_merge_20221201_1745'),
        ('AmadeusDecoder', '0168_merge_20221205_1621'),
    ]

    operations = [
    ]
