# Generated by Django 3.2.15 on 2022-12-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0169_merge_20221205_1740'),
        ('AmadeusDecoder', '0169_passengerinvoice_invoice_id_passengerinvoice_status'),
    ]

    operations = [
    ]
