# Generated by Django 3.2.15 on 2022-12-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0170_merge_20221206_1851'),
        ('AmadeusDecoder', '0170_passengerinvoice_status'),
    ]

    operations = [
    ]
