# Generated by Django 4.0.7 on 2022-12-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0170_merge_20221206_1851'),
        ('AmadeusDecoder', '0170_passengerinvoice_status'),
    ]

    operations = [
    ]
