# Generated by Django 3.2.15 on 2022-12-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0171_merge_20221208_1347'),
        ('AmadeusDecoder', '0171_merge_20221208_1723'),
    ]

    operations = [
    ]
