# Generated by Django 4.0.6 on 2022-12-12 12:48

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0172_passengerinvoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeesEMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_value', models.DecimalField(decimal_places=4, default=0, max_digits=11)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fees_emd', to='AmadeusDecoder.companyinfo')),
            ],
            options={
                'db_table': 't_service_fees_emd',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='servicefeesemd',
            constraint=models.UniqueConstraint(fields=('company',), name='unique_service_fees_emd'),
        ),
    ]
