# Generated by Django 4.0.6 on 2022-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0173_servicefeesemd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_no_adc',
            field=models.BooleanField(default=0),
        ),
    ]
