# Generated by Django 4.0.6 on 2022-12-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0175_othersfee_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='other_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='AmadeusDecoder.othersfee'),
        ),
    ]
