# Generated by Django 4.0.6 on 2022-12-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0176_fee_other_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='AmadeusDecoder.ticket'),
        ),
    ]
