# Generated by Django 4.0.6 on 2022-12-14 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0177_alter_fee_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeesissoufali',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
