# Generated by Django 3.2.15 on 2022-12-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0172_merge_20221209_1844'),
        ('AmadeusDecoder', '0178_servicefeesissoufali_effective_date'),
    ]

    operations = [
    ]
