# Generated by Django 4.0.7 on 2022-12-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0181_passengerinvoice_status'),
        ('AmadeusDecoder', '0181_passengerinvoice_status_ticket_is_subjected_to_fees'),
    ]

    operations = [
    ]
