# Generated by Django 3.2.15 on 2022-12-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0181_passengerinvoice_status'),
        ('AmadeusDecoder', '0181_passengerinvoice_status_ticket_is_subjected_to_fees'),
    ]

    operations = [
    ]
