# Generated by Django 4.0.6 on 2022-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0181_passengerinvoice_status_ticket_is_subjected_to_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrpassenger',
            name='order',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
