# Generated by Django 4.0.7 on 2022-12-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0182_merge_20221227_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='passenger_segment',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='othersfee',
            name='reference',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
