# Generated by Django 4.0.6 on 2022-12-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0181_passengerinvoice_status'),
        ('AmadeusDecoder', '0182_pnrpassenger_order'),
    ]

    operations = [
    ]
