# Generated by Django 3.2.15 on 2022-12-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0181_passengerinvoice_status'),
        ('AmadeusDecoder', '0182_pnrpassenger_order'),
    ]

    operations = [
    ]
