# Generated by Django 4.0.7 on 2022-12-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0183_othersfee_passenger_segment_othersfee_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinvoice',
            name='other_fee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.othersfee'),
        ),
    ]
