# Generated by Django 4.0.6 on 2022-12-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0183_merge_20221229_0825'),
        ('AmadeusDecoder', '0184_passengerinvoice_other_fee_passengerinvoice_status'),
    ]

    operations = [
    ]
