# Generated by Django 3.2.15 on 2022-12-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0182_merge_20221219_1611'),
        ('AmadeusDecoder', '0185_merge_20221229_0830'),
    ]

    operations = [
    ]
