# Generated by Django 4.0.7 on 2022-12-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0185_merge_20221228_2210'),
        ('AmadeusDecoder', '0186_passengerinvoice_status'),
    ]

    operations = [
    ]
