# Generated by Django 4.0.7 on 2023-01-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0187_merge_20221230_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chart_of_accounts',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
