# Generated by Django 3.2.15 on 2023-01-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0187_merge_20221229_1743'),
        ('AmadeusDecoder', '0187_merge_20221230_0941'),
    ]

    operations = [
    ]
