# Generated by Django 3.2.15 on 2022-12-30 21:45

import AmadeusDecoder.models.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0188_passengerinvoice_status'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        migrations.CreateModel(
            name='Tjq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(default='', max_length=200)),
                ('tjq_agent_type', models.CharField(max_length=200)),
                ('doc_date', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('seq_no', models.CharField(max_length=200)),
                ('ticket_number', models.CharField(max_length=200)),
                ('pnr_number', models.CharField(max_length=200)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('comm', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('fp_pax', models.CharField(max_length=200)),
                ('passenger', models.CharField(max_length=200)),
                ('agent_code', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('system_creation_date', models.DateTimeField(null=True)),
                ('agency', models.ForeignKey(db_column='agency_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.office', to_field='code')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_tjq',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
