# Generated by Django 4.0.7 on 2023-01-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0188_client_chart_of_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creator_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(null=True),
        ),
    ]
