# Generated by Django 4.0.7 on 2023-01-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0189_client_creator_id_client_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
