# Generated by Django 3.2.15 on 2022-12-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0185_merge_20221228_2210'),
        ('AmadeusDecoder', '0189_auto_20221231_0045'),
    ]

    operations = [
    ]
