# Generated by Django 4.0.6 on 2023-01-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0187_merge_20221230_0941'),
        ('AmadeusDecoder', '0190_merge_20221231_0100'),
    ]

    operations = [
    ]
