# Generated by Django 4.0.7 on 2023-01-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0190_rename_creator_id_client_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
