# Generated by Django 4.0.6 on 2023-01-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0191_merge_20230103_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrairsegments',
            name='is_open',
            field=models.BooleanField(default=0),
        ),
    ]
