# Generated by Django 4.0.7 on 2023-01-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0193_merge_20230104_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinvoice',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='ticket',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket'),
        ),
    ]
