# Generated by Django 3.2.15 on 2023-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0188_merge_20230101_1858'),
        ('AmadeusDecoder', '0193_merge_20230103_1719'),
        ('AmadeusDecoder', '0194_passengerinvoice_date_creation_and_more'),
    ]

    operations = [
    ]
