# Generated by Django 4.0.6 on 2023-01-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0193_merge_20230103_1719'),
        ('AmadeusDecoder', '0194_passengerinvoice_date_creation_and_more'),
    ]

    operations = [
    ]
