# Generated by Django 3.2.15 on 2023-01-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0194_merge_20230103_1741'),
        ('AmadeusDecoder', '0196_passengerinvoice_status_and_more'),
    ]

    operations = [
    ]
