# Generated by Django 3.2.15 on 2023-01-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0195_merge_20230106_1003'),
        ('AmadeusDecoder', '0196_passengerinvoice_status_and_more'),
    ]

    operations = [
    ]
