# Generated by Django 4.0.7 on 2023-01-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0197_othersfee_creation_date'),
        ('AmadeusDecoder', '0198_auto_20230109_1435'),
    ]

    operations = [
    ]
