# Generated by Django 3.2.15 on 2023-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0198_auto_20230109_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinvoice',
            name='control',
            field=models.IntegerField(default=0),
        ),
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
