# Generated by Django 3.2.15 on 2023-01-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0197_merge_20230106_1847'),
        ('AmadeusDecoder', '0198_auto_20230109_1435'),
    ]

    operations = [
    ]
