# Generated by Django 3.2.15 on 2023-01-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0197_othersfee_creation_date'),
        ('AmadeusDecoder', '0198_auto_20230109_1435'),
    ]

    operations = [
    ]
