# Generated by Django 4.0.6 on 2023-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0199_merge_20230111_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='is_subjected_too_fee',
            field=models.BooleanField(default='1'),
        ),
    ]
