# Generated by Django 3.2.15 on 2023-01-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0200_othersfee_is_subjected_too_fee_and_more'),
    ]

    operations = [
    ]
