# Generated by Django 4.0.7 on 2023-01-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0199_merge_20230112_1034'),
        ('AmadeusDecoder', '0203_passengerinvoice_status'),
    ]

    operations = [
    ]
