# Generated by Django 4.0.6 on 2023-01-17 08:16

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0206_remove_notfetched_pnr_creation_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_text', models.TextField(default='')),
                ('data_datetime', models.DateTimeField(null=True)),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_data', to='AmadeusDecoder.pnr')),
            ],
            options={
                'db_table': 't_raw_data',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
