# Generated by Django 3.2.15 on 2023-01-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0200_merge_20230110_1722'),
        ('AmadeusDecoder', '0206_remove_notfetched_pnr_creation_and_more'),
    ]

    operations = [
    ]
