# Generated by Django 4.0.6 on 2023-01-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0199_auto_20230111_1640'),
        ('AmadeusDecoder', '0207_passengerinvoice_status_rawdata'),
    ]

    operations = [
    ]
