# Generated by Django 3.2.15 on 2023-01-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0199_auto_20230111_1640'),
        ('AmadeusDecoder', '0207_merge_20230112_1751'),
    ]

    operations = [
    ]
