# Generated by Django 3.2.15 on 2023-01-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0208_merge_20230116_1814'),
        ('AmadeusDecoder', '0209_rawdata_ticket'),
    ]

    operations = [
    ]
