# Generated by Django 4.0.6 on 2023-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0209_rawdata_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
    ]
