# Generated by Django 3.2.15 on 2023-01-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0210_merge_0208_merge_20230116_1814_0209_rawdata_ticket'),
        ('AmadeusDecoder', '0210_pnr_is_archived'),
    ]

    operations = [
    ]
