# Generated by Django 4.0.7 on 2023-01-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0210_pnr_is_archived'),
        ('AmadeusDecoder', '0212_othersfee_product_id_passengerinvoice_status'),
    ]

    operations = [
    ]
