# Generated by Django 3.2.15 on 2023-01-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0210_pnr_is_archived'),
        ('AmadeusDecoder', '0212_othersfee_product_id_passengerinvoice_status'),
    ]

    operations = [
    ]
