# Generated by Django 4.0.7 on 2023-01-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0213_merge_20230123_0659'),
        ('AmadeusDecoder', '0213_merge_20230123_1457'),
    ]

    operations = [
    ]
