# Generated by Django 4.0.6 on 2023-01-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0213_merge_20230123_1628'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='othersfee',
        #     name='creation_date',
        #     field=models.DateField(auto_now=True),
        # ),
    ]
