# Generated by Django 3.2.15 on 2023-01-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0211_merge_20230120_1837'),
        ('AmadeusDecoder', '0213_merge_20230123_0659'),
        ('AmadeusDecoder', '0213_merge_20230123_1457'),
        ('AmadeusDecoder', '0214_passengerinvoice_status_and_more'),
    ]

    operations = [
    ]
