# Generated by Django 4.0.6 on 2023-01-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0213_merge_20230123_0659'),
        ('AmadeusDecoder', '0213_merge_20230123_1457'),
        ('AmadeusDecoder', '0214_passengerinvoice_status_and_more'),
    ]

    operations = [
    ]
