# Generated by Django 3.2.15 on 2023-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0215_merge_20230123_1734'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='othersfee',
        #     name='creation_date',
        #     field=models.DateField(auto_now=True, null=True),
        # ),
    ]
