# Generated by Django 4.0.6 on 2023-01-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0216_alter_othersfee_creation_date'),
        ('AmadeusDecoder', '0216_pnrairsegments_air_segment_status'),
    ]

    operations = [
    ]
