# Generated by Django 3.2.15 on 2023-01-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0214_merge_20230123_1514'),
        ('AmadeusDecoder', '0217_merge_20230124_1331'),
    ]

    operations = [
    ]
