# Generated by Django 4.0.7 on 2023-01-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0214_merge_20230123_1514'),
        ('AmadeusDecoder', '0217_merge_20230124_1331'),
    ]

    operations = [
    ]
