# Generated by Django 3.2.15 on 2023-01-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0218_merge_20230126_0711'),
        ('AmadeusDecoder', '0218_merge_20230126_1449'),
    ]

    operations = [
    ]
