# Generated by Django 4.0.7 on 2023-01-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0218_merge_20230126_0711'),
        ('AmadeusDecoder', '0218_merge_20230126_1449'),
    ]

    operations = [
    ]
