# Generated by Django 3.2.15 on 2023-01-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0195_merge_20230105_1916'),
        ('AmadeusDecoder', '0219_merge_20230128_0900'),
    ]

    operations = [
    ]
