# Generated by Django 3.2.15 on 2023-01-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0220_merge_20230128_1308'),
        ('AmadeusDecoder', '0220_passengerinvoice_status_and_more'),
    ]

    operations = [
    ]
