# Generated by Django 4.0.6 on 2023-02-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0219_merge_20230128_0900'),
        ('AmadeusDecoder', '0220_passengerinvoice_status_and_more'),
    ]

    operations = [
    ]
