# Generated by Django 4.0.7 on 2023-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0221_merge_20230201_1441'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='invoice_number',
        #     field=models.CharField(default=None, max_length=100, null=True),
        # ),
    ]
