# Generated by Django 3.2.15 on 2023-02-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0221_merge_20230131_1608'),
        ('AmadeusDecoder', '0221_merge_20230201_1441'),
    ]

    operations = [
    ]
