# Generated by Django 4.0.7 on 2023-02-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0186_merge_20221229_0918'),
        ('AmadeusDecoder', '0222_merge_20230201_1705'),
        ('AmadeusDecoder', '0222_passengerinvoice_invoice_number_and_more'),
    ]

    operations = [
    ]
