# Generated by Django 4.0.6 on 2023-02-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0186_merge_20221229_0918'),
        ('AmadeusDecoder', '0222_merge_20230201_1705'),
    ]

    operations = [
    ]
