# Generated by Django 4.0.6 on 2023-02-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0223_merge_20230204_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinvoice',
            name='invoice_number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
