# Generated by Django 3.2.15 on 2023-02-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0223_merge_20230204_1035'),
        ('AmadeusDecoder', '0224_auto_20230204_1133'),
        ('AmadeusDecoder', '0224_passengerinvoice_invoice_number_and_more'),
    ]

    operations = [
    ]
