# Generated by Django 4.0.6 on 2023-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0225_merge_20230204_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='other_fee_status',
            field=models.IntegerField(default=1),
        ),
    ]
