# Generated by Django 4.0.6 on 2023-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0227_merge_20230208_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='related_passenger_order',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
