# Generated by Django 4.0.6 on 2023-02-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0228_passengerinvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='AmadeusDecoder.companyinfo'),
        ),
    ]
