# Generated by Django 4.0.6 on 2023-02-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0228_merge_20230209_1205'),
        ('AmadeusDecoder', '0229_office_company'),
    ]

    operations = [
    ]
