# Generated by Django 4.0.6 on 2023-02-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0230_merge_0228_merge_20230209_1205_0229_office_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othersfee',
            old_name='is_subjected_too_fee',
            new_name='is_subjected_to_fee',
        ),
    ]
