# Generated by Django 3.2.15 on 2023-02-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0232_merge_20230210_1840'),
        ('AmadeusDecoder', '0232_merge_20230213_1705'),
    ]

    operations = [
    ]
