# Generated by Django 4.0.6 on 2023-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0233_passengerinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_refund',
            field=models.BooleanField(default=0),
        ),
    ]
