# Generated by Django 4.0.6 on 2023-02-27 11:35

import AmadeusDecoder.models.BaseModel
from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0234_ticket_is_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('modification_type', models.CharField(max_length=100)),
                ('modification', django.contrib.postgres.fields.hstore.HStoreField()),
                ('modification_date', models.DateTimeField()),
                ('pnr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='AmadeusDecoder.pnr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_history',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
