# Generated by Django 3.2.15 on 2023-02-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0233_merge_20230213_1758'),
        ('AmadeusDecoder', '0234_ticket_is_refund'),
    ]

    operations = [
    ]
