# Generated by Django 3.2.15 on 2023-02-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0235_history'),
        ('AmadeusDecoder', '0235_merge_0233_merge_20230213_1758_0234_ticket_is_refund'),
    ]

    operations = [
    ]
