# Generated by Django 4.0.6 on 2023-03-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0236_passengerinvoice_status_ticket_is_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_fees', to='AmadeusDecoder.passenger'),
        ),
        # migrations.AddField(
        #     model_name='passengerinvoice',
        #     name='status',
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
