# Generated by Django 4.1.7 on 2023-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0237_othersfee_passenger_passengerinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_issued_outside',
            field=models.BooleanField(default=0),
        ),
    ]
