# Generated by Django 3.2.15 on 2023-03-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0237_merge_20230308_1737'),
        ('AmadeusDecoder', '0238_ticket_is_issued_outside'),
    ]

    operations = [
    ]
