# Generated by Django 4.1.7 on 2023-03-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0239_officesubcontractor_passengerinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerinvoice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
