# Generated by Django 3.2.15 on 2023-03-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0240_merge_20230320_1754'),
        ('AmadeusDecoder', '0240_passengerinvoice_is_archived_passengerinvoice_status'),
    ]

    operations = [
    ]
