# Generated by Django 3.2.15 on 2023-03-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0241_merge_20230321_1640'),
        ('AmadeusDecoder', '0242_ticket_is_not_fa_line'),
    ]

    operations = [
    ]
