# Generated by Django 4.1.7 on 2023-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0244_passenger_passenger_status_passengerinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othersfee',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
