# Generated by Django 4.1.7 on 2023-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0244_passenger_passenger_status_passengerinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='odoo_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
