# Generated by Django 3.2.15 on 2023-05-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0245_alter_othersfee_creation_date'),
        ('AmadeusDecoder', '0245_client_odoo_id'),
    ]

    operations = [
    ]
