# Generated by Django 4.1.7 on 2023-06-01 11:57

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0246_othersfee_other_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='AmadeusDecoder.passenger')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerAddresses', to='AmadeusDecoder.pnr')),
            ],
            options={
                'db_table': 't_customer_address',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
