# Generated by Django 3.2.15 on 2023-05-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0246_merge_20230515_1419'),
        ('AmadeusDecoder', '0246_othersfee_other_fee'),
    ]

    operations = [
    ]
