# Generated by Django 4.1.7 on 2023-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0247_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_gp',
            field=models.BooleanField(default=0),
        ),
    ]
