# Generated by Django 3.2.15 on 2023-06-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0247_merge_20230526_1438'),
        ('AmadeusDecoder', '0248_ticket_is_gp'),
    ]

    operations = [
    ]
