# Generated by Django 4.0 on 2023-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0248_ticket_is_gp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issuing_agency_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
