# Generated by Django 4.2.2 on 2023-07-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0249_merge_0247_merge_20230526_1438_0248_ticket_is_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinvoice',
            name='fee',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.fee', unique=True),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='other_fee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.othersfee', unique=True),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='ticket',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket', unique=True),
        ),
    ]
