# Generated by Django 4.2.2 on 2023-07-07 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0250_alter_passengerinvoice_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='emitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emitted_other_fees', to=settings.AUTH_USER_MODEL),
        ),
    ]
