# Generated by Django 4.0 on 2023-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0250_othersfee_issuing_agency_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassSign',
            new_name='ClassCabin',
        ),
        migrations.RenameModel(
            old_name='ServiceFeesIssoufali',
            new_name='ServiceFeesAmountBased',
        ),
        migrations.RenameModel(
            old_name='ServiceFeesMercure',
            new_name='ServiceFeesClassBased',
        ),
        migrations.AddConstraint(
            model_name='flightclass',
            constraint=models.UniqueConstraint(fields=('flightclass',), name='unique_flight_class'),
        ),
        migrations.AddConstraint(
            model_name='flighttype',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_flight_type'),
        ),
        migrations.AlterModelTable(
            name='classcabin',
            table='t_class_cabin',
        ),
    ]
