# Generated by Django 3.2.15 on 2023-06-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0249_merge_0247_merge_20230526_1438_0248_ticket_is_gp'),
        ('AmadeusDecoder', '0250_othersfee_issuing_agency_name'),
    ]

    operations = [
    ]
