# Generated by Django 4.0 on 2023-06-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0249_merge_0247_merge_20230526_1438_0248_ticket_is_gp'),
        ('AmadeusDecoder', '0251_rename_classsign_classcabin_and_more'),
    ]

    operations = [
    ]
