# Generated by Django 4.2.2 on 2023-07-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0251_othersfee_emitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerinvoice',
            name='fee',
            field=models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.fee'),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='other_fee',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.othersfee'),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='ticket',
            field=models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket'),
        ),
    ]
