# Generated by Django 4.0 on 2023-06-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0253_history_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='object_id',
            new_name='related_object_id',
        ),
    ]
