# Generated by Django 4.0 on 2023-07-03 07:30

import AmadeusDecoder.models.BaseModel
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0254_rename_object_id_history_related_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('to_be_applied_on', models.CharField(max_length=255)),
                ('value_name', models.CharField(max_length=255)),
                ('single_value', models.TextField()),
                ('array_value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None)),
                ('array_of_array_value', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), null=True, size=None), null=True, size=None)),
                ('dict_value', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('created_on', models.DateTimeField()),
                ('last_udpate', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 't_configuration',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
        migrations.AddConstraint(
            model_name='configuration',
            constraint=models.UniqueConstraint(fields=('environment', 'name', 'value_name'), name='unique_configuration'),
        ),
    ]
