# Generated by Django 4.0 on 2023-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0255_configuration_configuration_unique_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='single_value',
            field=models.TextField(null=True),
        ),
    ]
