# Generated by Django 4.0 on 2023-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0257_rename_last_udpate_configuration_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='environment',
            field=models.CharField(default='all', max_length=10),
        ),
    ]
