# Generated by Django 4.0 on 2023-07-04 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0258_alter_configuration_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='array_of_array_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), blank=True, null=True, size=None),
        ),
    ]
