# Generated by Django 4.0 on 2023-07-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0259_alter_configuration_array_of_array_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='date_value',
            field=models.DateTimeField(null=True),
        ),
    ]
