# Generated by Django 4.0 on 2023-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0260_configuration_date_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='regionalflight',
            name='unique_region_company',
        ),
        migrations.RemoveField(
            model_name='regionalflight',
            name='company',
        ),
        migrations.AddConstraint(
            model_name='regionalflight',
            constraint=models.UniqueConstraint(fields=('country',), name='unique_region_company'),
        ),
    ]
