# Generated by Django 3.2.15 on 2023-07-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0251_merge_20230621_1224'),
        ('AmadeusDecoder', '0260_configuration_date_value'),
    ]

    operations = [
    ]
