# Generated by Django 4.0 on 2023-08-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0261_remove_regionalflight_unique_region_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='emitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emitted_other_fees', to='AmadeusDecoder.user'),
        ),
        migrations.AddField(
            model_name='othersfee',
            name='issuing_agent_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
