# Generated by Django 4.2.2 on 2023-07-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0252_alter_passengerinvoice_fee_and_more'),
        ('AmadeusDecoder', '0261_remove_regionalflight_unique_region_company_and_more'),
    ]

    operations = [
    ]
