# Generated by Django 3.2.15 on 2023-07-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0261_merge_20230707_0722'),
        ('AmadeusDecoder', '0261_remove_regionalflight_unique_region_company_and_more'),
    ]

    operations = [
    ]
