# Generated by Django 4.0 on 2023-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0262_othersfee_emitter_othersfee_issuing_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issuing_agent_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
