# Generated by Django 4.2.2 on 2023-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0262_merge_20230720_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
