# Generated by Django 4.2.2 on 2023-08-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0262_merge_20230711_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='fee',
            field=models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.fee'),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='other_fee',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.othersfee'),
        ),
        migrations.AlterField(
            model_name='passengerinvoice',
            name='ticket',
            field=models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket'),
        ),
    ]
