# Generated by Django 4.0 on 2023-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0263_ticket_issuing_agent_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pnr',
            name='unique_pnr',
        ),
        migrations.AddField(
            model_name='pnr',
            name='pnr_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='pnr',
            constraint=models.UniqueConstraint(fields=('number', 'pnr_status'), name='unique_pnr'),
        ),
    ]
