# Generated by Django 3.2.15 on 2023-08-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0263_auto_20230725_1239'),
        ('AmadeusDecoder', '0264_remove_pnr_unique_pnr_pnr_pnr_status_pnr_unique_pnr'),
    ]

    operations = [
    ]
