# Generated by Django 3.2.15 on 2023-08-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0263_alter_configuration_created_on_and_more'),
        ('AmadeusDecoder', '0265_merge_20230810_1352'),
    ]

    operations = [
    ]
