# Generated by Django 4.0 on 2023-09-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0266_merge_20230817_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fee',
            name='newest_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fee',
            name='old_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fee',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fee',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fee',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='total_fees',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='total_tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='totalht',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tva_sce',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='othersfee',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='othersfee',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='othersfee',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='othersfee',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='reducepnrfeerequest',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='reducepnrfeerequest',
            name='origin_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='servicefeesamountbased',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='servicefeesamountbased',
            name='max_interval',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='servicefeesamountbased',
            name='min_interval',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='servicefeesclassbased',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='servicefeesemd',
            name='fee_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='servicefeesprime',
            name='fee_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='tax',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='exch_val',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fare',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fareequiv',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='farerate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='rfnd_val',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='transport_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=13),
        ),
    ]
