# Generated by Django 4.2.6 on 2023-10-09 08:20

import AmadeusDecoder.models.BaseModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0267_alter_fee_cost_alter_fee_newest_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('code_region', models.IntegerField()),
            ],
            options={
                'db_table': 't_departments',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
