# Generated by Django 3.2.15 on 2023-12-08 09:03

import AmadeusDecoder.models.BaseModel
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0269_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesCanceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('other_fee', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.othersfee')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.pnr')),
                ('ticket', models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket')),
            ],
            options={
                'db_table': 't_invoices_canceled',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
