# Generated by Django 3.2.15 on 2023-12-11 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0270_invoicescanceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescanceled',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_canceled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
