# Generated by Django 3.2.15 on 2023-12-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0271_auto_20231211_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescanceled',
            name='fee',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.fee'),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
