# Generated by Django 3.2.15 on 2023-12-18 07:25

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0272_auto_20231212_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicescanceled',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='fee',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered_fee', to='AmadeusDecoder.fee'),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='motif',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='other_fee',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered_other_fee', to='AmadeusDecoder.othersfee'),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered', to='AmadeusDecoder.pnr'),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='ticket',
            field=models.OneToOneField(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered_ticket', to='AmadeusDecoder.ticket'),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100, null=True)),
                ('infos', django.contrib.postgres.fields.hstore.HStoreField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(default=0)),
                ('accept_date', models.DateTimeField(auto_now=True, null=True)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('issuing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuing_user', to=settings.AUTH_USER_MODEL)),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.pnr')),
            ],
            options={
                'db_table': 't_anomalie',
            },
        ),
    ]
