# Generated by Django 3.2.15 on 2023-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0273_auto_20231218_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalie',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='accept_date',
            field=models.DateTimeField(null=True),
        ),
    ]
