# Generated by Django 3.2.15 on 2023-12-27 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0274_auto_20231218_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalie',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
