# Generated by Django 3.2.15 on 2023-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0275_auto_20231227_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
