# Generated by Django 3.2.15 on 2024-01-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0270_alter_othersfee_creation_date'),
        ('AmadeusDecoder', '0276_alter_anomalie_creation_date'),
    ]

    operations = [
    ]
