# Generated by Django 3.2.15 on 2024-01-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0277_merge_20240118_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalie',
            old_name='accept_date',
            new_name='response_date',
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
