# Generated by Django 3.2.15 on 2024-02-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0271_pnr_is_canceled'),
        ('AmadeusDecoder', '0278_auto_20240118_0628'),
    ]

    operations = [
    ]
