# Generated by Django 3.2.15 on 2024-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0278_auto_20240118_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='config',
            name='type',
        ),
        migrations.RemoveField(
            model_name='config',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='config',
            name='value',
        ),
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='config',
            name='to_be_applied_on',
            field=models.CharField(default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='config',
            name='value_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
