# Generated by Django 3.2.15 on 2024-02-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0279_merge_0271_pnr_is_canceled_0278_auto_20240118_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='is_canceled',
        ),
    ]
