# Generated by Django 5.0.2 on 2024-02-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0279_auto_20240219_1037'),
        ('AmadeusDecoder', '0280_remove_pnr_is_canceled'),
    ]

    operations = [
    ]
