# Generated by Django 3.2.15 on 2024-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0280_remove_pnr_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reducepnrfeerequest',
            name='system_creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
