# Generated by Django 3.2.15 on 2024-07-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0281_alter_reducepnrfeerequest_system_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifPnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_motif_pnr',
            },
        ),
        
    ]
