# Generated by Django 3.2.15 on 2024-04-24 11:12

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0281_alter_reducepnrfeerequest_system_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnremountedPnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(null=True)),
                ('passengers_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('segments_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('tickets_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('state', models.IntegerField(default=0)),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_unremouted_pnr',
            },
        ),
    ]
