# Generated by Django 3.2.15 on 2024-07-31 11:26

import AmadeusDecoder.models.BaseModel
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0281_alter_reducepnrfeerequest_system_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifPnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 't_motif_pnr',
            },
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='admin_id',
        ),
        migrations.CreateModel(
            name='TicketCanceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(max_length=200)),
                ('issuing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('other_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.othersfee')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.pnr')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket')),
            ],
            options={
                'db_table': 't_ticket_canceled',
            },
            bases=(models.Model, AmadeusDecoder.models.BaseModel.BaseModel),
        ),
    ]
