# Generated by Django 5.0.2 on 2024-02-22 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0281_merge_20240222_1227'),
    ]

    operations = [
       
    ]
