# Generated by Django 5.1.3 on 2024-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='OptimisedPnrList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('passengers', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('emitter', models.CharField(max_length=255)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_office_code', models.CharField(max_length=255)),
                ('agency_office_name', models.CharField(max_length=255)),
                ('is_invoiced', models.BooleanField(db_index=True)),
                ('date_of_creation', models.DateTimeField(db_index=True)),
                ('is_read', models.BooleanField()),
                ('status_value', models.IntegerField()),
                ('state', models.IntegerField()),
                ('client', models.CharField(max_length=255)),
                ('pnr_comment_state', models.IntegerField()),
                ('pnr_min_doc_state', models.DateTimeField(db_index=True)),
                ('max_issuing_date', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'optimised_pnr_list',
                'managed': False,
            },
        ),
    ]
