# Generated by Django 3.2.15 on 2024-07-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0282_auto_20240717_1018'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='othersfee',
            name='value',
        ),
    ]
