# Generated by Django 3.2.15 on 2024-07-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0282_auto_20240708_1204'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='invoicescanceled',
            name='motif_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='motif_pnr', to='AmadeusDecoder.motifpnr'),
        ),
    ]
