# Generated by Django 3.2.15 on 2024-04-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0282_auto_20240424_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_passenger_type',
            },
        ),
        migrations.CreateModel(
            name='unRemountedPnrPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('passeport', models.CharField(max_length=100, null=True)),
                ('order', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.passengertype')),
            ],
            options={
                'db_table': 't_unremounted_pnr_passenger',
            },
        ),
        migrations.CreateModel(
            name='unRemountedPnrSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightno', models.CharField(max_length=50, null=True)),
                ('departuretime', models.DateTimeField(null=True)),
                ('arrivaltime', models.DateTimeField(null=True)),
                ('codedest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_code', to='AmadeusDecoder.airport')),
                ('codeorg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_code', to='AmadeusDecoder.airport')),
            ],
            options={
                'db_table': 't_unremounted_pnr_segment',
            },
        ),
        migrations.RemoveField(
            model_name='unremountedpnr',
            name='passengers_data',
        ),
        migrations.RemoveField(
            model_name='unremountedpnr',
            name='segments_data',
        ),
        migrations.RemoveField(
            model_name='unremountedpnr',
            name='tickets_data',
        ),
        migrations.CreateModel(
            name='unRemountedTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=5, null=True)),
                ('transport_cost', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=13)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnrpassenger')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnrsegment')),
                ('unremountedPnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnr')),
            ],
            options={
                'db_table': 't_unremounted_pnr_ticket',
            },
        ),
        migrations.AddField(
            model_name='unremountedpnrsegment',
            name='unremountedPnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnr'),
        ),
        migrations.AddField(
            model_name='unremountedpnrpassenger',
            name='unremountedPnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnr'),
        ),
    ]
