# Generated by Django 3.2.15 on 2024-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0283_refunds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='emitter',
            field=models.CharField(max_length=255),
        ),
    ]
