# Generated by Django 3.2.15 on 2024-07-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0283_auto_20240709_1352'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='invoicescanceled',
            name='motif',
        ),
    ]
