# Generated by Django 3.2.15 on 2024-03-06 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0283_remove_anomalie_admin_id_anomalie_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='issuing_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuing_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reducepnrfeerequest',
            name='system_creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
