# Generated by Django 3.2.15 on 2024-07-19 07:09

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0283_auto_20240719_1008'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='othersfee',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
