# Generated by Django 3.2.15 on 2024-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0284_auto_20240426_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unRemountedTickets',
            new_name='unRemountedPnrTickets',
        ),
        migrations.AlterField(
            model_name='unremountedpnr',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
