# Generated by Django 3.2.15 on 2024-04-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0281_alter_reducepnrfeerequest_system_creation_date'),
        ('AmadeusDecoder', '0284_auto_20240306_1146'),
    ]

    operations = [
    ]
