# Generated by Django 5.1.3 on 2024-11-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0283_optimisedpnrlist'),
        ('AmadeusDecoder', '0284_auto_20240709_1402'),
    ]

    operations = [
    ]
