# Generated by Django 3.2.15 on 2024-06-24 14:10

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0284_alter_refunds_emitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='emitter',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
