# Generated by Django 3.2.15 on 2024-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0285_auto_20240429_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='unremountedpnrtickets',
            name='fee',
            field=models.BooleanField(default=True),
        ),
    ]
