# Generated by Django 3.2.15 on 2024-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0285_merge_20240418_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieAnomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 't_categorie_anomalie',
            },
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='admin',
        ),
    ]
