# Generated by Django 3.2.15 on 2024-06-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0285_alter_refunds_emitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
