# Generated by Django 3.2.15 on 2025-01-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0285_merge_0283_optimisedpnrlist_0284_auto_20240709_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicescanceled',
            name='other_fee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered_other_fees', to='AmadeusDecoder.othersfee'),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='ticket',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered_tickets', to='AmadeusDecoder.ticket'),
        ),
    ]
