# Generated by Django 3.2.15 on 2025-02-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0284_auto_20240719_1009'),
        ('AmadeusDecoder', '0285_merge_0283_optimisedpnrlist_0284_auto_20240709_1402'),
    ]

    operations = [
    ]
