# Generated by Django 3.2.15 on 2025-04-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0286_merge_20250225_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfetched',
            name='context',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notfetched',
            name='status',
            field=models.IntegerField(default=0),
        )
    ]
