# Generated by Django 3.2.15 on 2024-04-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0286_auto_20240429_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='unremountedpnrsegment',
            name='servicecarrier',
            field=models.ForeignKey(default=1605, on_delete=django.db.models.deletion.CASCADE, related_name='segment_airline', to='AmadeusDecoder.airline'),
        ),
    ]
