# Generated by Django 3.2.15 on 2024-06-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0286_alter_refunds_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='is_ticket_refund_exist',
            field=models.BooleanField(default=False),
        ),
    ]
