# Generated by Django 3.2.15 on 2025-03-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0286_merge_20250225_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicescanceled',
            name='fee',
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='other_fee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered_other_fees', to='AmadeusDecoder.othersfee'),
        ),
        migrations.AlterField(
            model_name='invoicescanceled',
            name='ticket',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnr_unordered_tickets', to='AmadeusDecoder.ticket'),
        ),
    ]
