# Generated by Django 3.2.15 on 2025-01-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0286_auto_20250116_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicescanceled',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
