# Generated by Django 3.2.15 on 2024-04-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0287_auto_20240430_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unremountedpnrsegment',
            name='servicecarrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_airline', to='AmadeusDecoder.airline'),
        ),
    ]
