# Generated by Django 3.2.15 on 2025-12-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0287_auto_20250317_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfetched',
            name='context',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notfetched',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notfetched',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notfetched',
            name='pnr_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
