# Generated by Django 3.2.15 on 2025-01-17 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0288_auto_20250116_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicescanceled',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
