# Generated by Django 3.2.15 on 2024-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0288_auto_20240430_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='unremountedpnrtickets',
            name='ticket_type',
            field=models.IntegerField(default=0),
        ),
    ]
