# Generated by Django 3.2.15 on 2025-01-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0289_auto_20250117_0711'),
    ]

    operations = [

        migrations.AddField(
            model_name='invoicescanceled',
            name='motif_odoo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
