# Generated by Django 3.2.15 on 2024-05-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0289_auto_20240502_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unremountedpnrtickets',
            name='segment',
        ),
        migrations.CreateModel(
            name='unRemountedPnrTicketSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnrsegment')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnrtickets')),
            ],
            options={
                'db_table': 't_unremounted_pnt_ticket_segment',
            },
        ),
    ]
