# Generated by Django 3.2.15 on 2024-06-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0288_ticketcanceled'),
        ('AmadeusDecoder', '0290_auto_20240516_1512'),
    ]

    operations = [
    ]
