# Generated by Django 3.2.15 on 2024-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0290_auto_20240516_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unremountedpnrtickets',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
