# Generated by Django 3.2.15 on 2025-01-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0290_auto_20250120_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicescanceled',
            name='motif_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motif_pnr', to='AmadeusDecoder.motifpnr'),
        ),
    ]
