# Generated by Django 3.2.15 on 2024-06-17 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0291_auto_20240531_1230'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='unremountedpnr',
            name='emitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
