# Generated by Django 3.2.15 on 2024-06-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0291_auto_20240531_1230'),
        ('AmadeusDecoder', '0291_merge_0288_ticketcanceled_0290_auto_20240516_1512'),
    ]

    operations = [
    ]
