# Generated by Django 5.1.3 on 2025-02-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0292_auto_20250120_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescanceled',
            name='last_info',
            field=models.JSONField(null=True, verbose_name='Ancienne information'),
        ),
    ]
