# Generated by Django 3.2.15 on 2024-06-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0292_merge_20240606_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicescanceled',
            name='fee',
        ),
    ]
