# Generated by Django 3.2.15 on 2024-06-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0292_auto_20240617_1116'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='unremountedpnrtickets',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.unremountedpnrpassenger'),
        ),
    ]
