# Generated by Django 5.1.3 on 2025-02-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0293_remove_anomalie_admin_id_invoicescanceled_last_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescanceled',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
