# Generated by Django 3.2.15 on 2024-06-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0293_remove_invoicescanceled_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescanceled',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
