# Generated by Django 3.2.15 on 2024-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0294_invoicescanceled_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='categorie',
            field=models.CharField(max_length=250),
        ),
    ]
