# Generated by Django 5.1.3 on 2025-03-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0294_remove_anomalie_admin_id_remove_invoicescanceled_fee_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='comment',
            name='user_odoo',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
