# Generated by Django 3.2.15 on 2024-10-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0284_auto_20240719_1009'),
        ('AmadeusDecoder', '0295_alter_anomalie_categorie'),
    ]

    operations = [
    ]
