# Generated by Django 3.2.15 on 2024-10-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0296_merge_20241030_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimisedPnrList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('passengers', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('emitter', models.CharField(max_length=255)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_office_code', models.CharField(max_length=255)),
                ('agency_office_name', models.CharField(max_length=255)),
                ('is_invoiced', models.BooleanField(db_index=True)),
                ('date_of_creation', models.DateTimeField(db_index=True)),
                ('is_read', models.BooleanField()),
                ('status_value', models.IntegerField()),
                ('state', models.IntegerField()),
                ('client', models.CharField(max_length=255)),
                ('pnr_comment_state', models.IntegerField()),
                ('pnr_min_doc_state', models.DateTimeField(db_index=True)),
                ('max_issuing_date', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'optimised_pnr_list',
                'managed': False,
            },
        ),
        
        migrations.RemoveField(
            model_name='othersfee',
            name='value',
        ),
        migrations.CreateModel(
            name='CancelSaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.client')),
                ('fee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.fee')),
                ('other_fee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.othersfee')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_sale_orders', to='AmadeusDecoder.pnr')),
                ('ticket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AmadeusDecoder.ticket')),
            ],
            options={
                'db_table': 't_cancel_sale_order',
            },
        ),
    ]
