# Generated by Django 3.2.15 on 2024-10-30 12:38

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmadeusDecoder', '0297_auto_20241030_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersfee',
            name='value',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
